FROM alpine:3.8

EXPOSE 80

ARG NGINX_VERSION=1.14.2

ENV NGINX_RESOLVERS="8.8.8.8 8.8.4.4 1.1.1.1 1.0.0.1"
ENV NGINX_RESOLVER_VALID="300s"
ENV NGINX_RESOLVER_TIMEOUT="60s"
ENV NGINX_CLIENT_BODY_SIZE_MAX=32m
ENV NGINX_PROXY_READ_TIMEOUT=30s
ENV NGINX_PROXY_SEND_TIMEOUT=30s
ENV NGINX_SEND_TIMEOUT=30s

COPY src /
RUN nginx-setup

HEALTHCHECK CMD nginx-healthcheck
ENTRYPOINT ["nginx-entrypoint"]
CMD ["nginx"]
